import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: '📈 ZarSimShop.ir | Gold & Silver Bullion | فروش شمش طلا و نقره ',
  description:  'فروش شمش طلا و نقره ، سرمایه گذاری امن با ضمانت و فاکتور رسمی ، ارسال سریع به سراسر کشور ، شماره تلفن ثبت سفارش 09120270308',
  keywords:
   ['قیمت طلا',
     'قیمت ارز',
     'تحلیل قیمت',
     'هوش مصنوعی',
     'اخبار اقتصادی',
     'تشخیص روند',
      'قیمت دلار',
       'سکه امامی',
        'انس جهانی',
         'دلار تتر',
          'قیمت لحظه‌ای طلا',
        'قیمت لحظه ای نقره' ,
        'شمش',
        'نقره',
         'طلا',
        'فروش شمش',
         'شمش طلا',
        'شمش نقره',
         'سرمایه گذاری',
        'ضمانت',
         'فاکتور رسمی',
        'zarsimshop',
         'zarsimshop.ir',
        'زرسیم',
         'زرسیم شاپ',
        'شاپ'

        
        ],
  alternates: {
    canonical: 'https://ZarSimShop.ir',
  },
  openGraph: {
    title:  '📈 ZarSimShop.ir | Gold & Silver Bullion | فروش شمش طلا و نقره ',
  description:  'فروش شمش طلا و نقره ، سرمایه گذاری امن با ضمانت و فاکتور رسمی ، ارسال سریع به سراسر کشور ، شماره تلفن ثبت سفارش 09120270308',
    url: 'https://ZarSimShop.ir',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}



// app/market/layout.tsx


// export default function MarketLayout({ children }: { children: React.ReactNode }) {
//   return <>{children}</>;
// }